
name: build-prerelease

on:
  workflow_dispatch:
  
jobs:
  
  build-Linux:
    runs-on: ubuntu-20.04 
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15
      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: install other requirements
        run : |
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          python3 -m pip install patchelf
      - name: Build
        run: python3 build.py --build cx_freeze
      
      - name: compress archive
        run: |
          mv dist/ bin/
          zip -r REAL-Video-Enhancer-2.2.5-Linux.zip bin/

      - name: compress backend
        run: |
          tar czf backend-v2.2.5.tar.gz backend/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: REAL-Video-Enhancer-2.2.5-Linux.zip
          path: REAL-Video-Enhancer-2.2.5-Linux.zip

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-v2.2.5.tar.gz 
          path: backend-v2.2.5.tar.gz 
          
  build-Windows:
    runs-on: windows-2019
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
          
      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r requirements.txt
      

      - name: Build
        run: python3 build.py --build pyinstaller
      
      - name: compress archive
        run: |
            cd dist
            tar -a -c -f REAL-Video-Enhancer-2.2.5-Windows.zip REAL-Video-Enhancer
            cd ..
            cp dist/REAL-Video-Enhancer-2.2.5-Windows.zip REAL-Video-Enhancer-2.2.5-Windows.zip

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: REAL-Video-Enhancer-2.2.5-Windows.zip
          path: REAL-Video-Enhancer-2.2.5-Windows.zip

  build-MacOS:
    runs-on: macos-13
    permissions: write-all  
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - name: Install Python Dependencies

        run: |

          brew install llvm@15
          brew install pyside
          python3 -m pip install -r requirements.txt

      - name: Build

        run: python3 build.py --build pyinstaller
    
      - name: compress archive
        run: |
          zip -r REAL-Video-Enhancer-2.2.5-MacOS_x86_64.zip dist/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: REAL-Video-Enhancer-2.2.5-MacOS_x86_64.zip
          path: REAL-Video-Enhancer-2.2.5-MacOS_x86_64.zip

  build-MacOS_arm64:

    runs-on: macos-14

    permissions: write-all  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python

        uses: actions/setup-python@v5

        with:
          python-version: 3.11.9

      - name: Install Python Dependencies
        run: |
          brew install pyside@6
          python3 -m pip install -r requirements.txt

      - name: Build
        run: |
          python3 build.py --build pyinstaller

      - name: compress archive
        run: |


          zip -r REAL-Video-Enhancer-2.2.5-MacOS_arm64.zip dist/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: REAL-Video-Enhancer-2.2.5-MacOS_arm64.zip
          path: REAL-Video-Enhancer-2.2.5-MacOS_arm64.zip
          
  Release:
    needs: [build-Windows, build-Linux, build-MacOS, build-MacOS_arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Generate version and tag
        id: version_tag
        run: |
          git clone https://github.com/tntwise/real-video-enhancer
          cp real-video-enhancer/CHANGELOG.md .
          version=$(python -c "from datetime import datetime; print(str(datetime.now()).split(' ')[0].replace('-',''))")
          tag=$(python -c "import random, string; print(''.join(random.choices(string.ascii_letters, k=8)))")
          python3 real-video-enhancer/scripts/printchangelog.py > RELEASE_BODY.md
          echo "Version=$version"
          echo "Tag=$version"
          echo "Body=$body"
          echo "::set-output name=version::$version"
          echo "::set-output name=tag::$version"
          
      - name: Compute SHA256 checksums
        run: |
          for file in artifacts/*; do
            for file1 in $file/*; do
              sha256sum "$file1" >> RELEASE_BODY.md
            done
          done
          
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1        
        with:
          name: REAL Video Enhancer 2.2.5 Pre-Release
          tag_name: RVE-2.2.5
          body_path: ./RELEASE_BODY.md
          draft: false
          prerelease: true
          
          files: |
              artifacts/REAL-Video-Enhancer-2.2.5-Windows.zip/REAL-Video-Enhancer-2.2.5-Windows.zip
              artifacts/REAL-Video-Enhancer-2.2.5-Linux.zip/REAL-Video-Enhancer-2.2.5-Linux.zip
              artifacts/REAL-Video-Enhancer-2.2.5-MacOS_x86_64.zip/REAL-Video-Enhancer-2.2.5-MacOS_x86_64.zip
              artifacts/REAL-Video-Enhancer-2.2.5-MacOS_arm64.zip/REAL-Video-Enhancer-2.2.5-MacOS_arm64.zip
              artifacts/backend-v2.2.5.tar.gz/backend-v2.2.5.tar.gz

              
              
        

     
